<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Import-numpy" data-toc-modified-id="Import-numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Import numpy</a></span></li><li><span><a href="#Build-a-numpy-array" data-toc-modified-id="Build-a-numpy-array-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Build a numpy array</a></span></li><li><span><a href="#Build-a-zero-array" data-toc-modified-id="Build-a-zero-array-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Build a zero array</a></span></li><li><span><a href="#Build-a-one-array" data-toc-modified-id="Build-a-one-array-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Build a one array</a></span></li><li><span><a href="#A-full-array" data-toc-modified-id="A-full-array-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>A full array</a></span></li><li><span><a href="#range-(like-range)" data-toc-modified-id="range-(like-range)-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>range (like range)</a></span></li><li><span><a href="#Find-the-values-in-the-range" data-toc-modified-id="Find-the-values-in-the-range-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Find the values in the range</a></span></li><li><span><a href="#Generate-value-randomly-from-0~1" data-toc-modified-id="Generate-value-randomly-from-0~1-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Generate value randomly from 0~1</a></span></li><li><span><a href="#Generate-value-randomly-from-normal-distribution" data-toc-modified-id="Generate-value-randomly-from-normal-distribution-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Generate value randomly from normal distribution</a></span></li><li><span><a href="#Generate-values-random-in-integars" data-toc-modified-id="Generate-values-random-in-integars-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Generate values random in integars</a></span></li><li><span><a href="#Generate-values-in-diagram" data-toc-modified-id="Generate-values-in-diagram-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Generate values in diagram</a></span></li><li><span><a href="#zero-value" data-toc-modified-id="zero-value-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>zero value</a></span></li><li><span><a href="#Index,-Slice" data-toc-modified-id="Index,-Slice-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Index, Slice</a></span></li><li><span><a href="#Reshape-the-array" data-toc-modified-id="Reshape-the-array-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Reshape the array</a></span></li><li><span><a href="#Concatenate-the-array" data-toc-modified-id="Concatenate-the-array-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>Concatenate the array</a></span></li><li><span><a href="#Split-the-array" data-toc-modified-id="Split-the-array-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>Split the array</a></span></li><li><span><a href="#absolute" data-toc-modified-id="absolute-17"><span class="toc-item-num">17&nbsp;&nbsp;</span>absolute</a></span></li><li><span><a href="#Exponential" data-toc-modified-id="Exponential-18"><span class="toc-item-num">18&nbsp;&nbsp;</span>Exponential</a></span></li><li><span><a href="#Power-the-array" data-toc-modified-id="Power-the-array-19"><span class="toc-item-num">19&nbsp;&nbsp;</span>Power the array</a></span></li><li><span><a href="#Log" data-toc-modified-id="Log-20"><span class="toc-item-num">20&nbsp;&nbsp;</span>Log</a></span></li><li><span><a href="#Multipliy" data-toc-modified-id="Multipliy-21"><span class="toc-item-num">21&nbsp;&nbsp;</span>Multipliy</a></span></li><li><span><a href="#Sum" data-toc-modified-id="Sum-22"><span class="toc-item-num">22&nbsp;&nbsp;</span>Sum</a></span></li><li><span><a href="#Max-Min" data-toc-modified-id="Max-Min-23"><span class="toc-item-num">23&nbsp;&nbsp;</span>Max Min</a></span></li><li><span><a href="#argmax-argmin" data-toc-modified-id="argmax-argmin-24"><span class="toc-item-num">24&nbsp;&nbsp;</span>argmax argmin</a></span></li><li><span><a href="#Extract-the-percent-value-from-the-array" data-toc-modified-id="Extract-the-percent-value-from-the-array-25"><span class="toc-item-num">25&nbsp;&nbsp;</span>Extract the percent value from the array</a></span></li><li><span><a href="#Find-the-median" data-toc-modified-id="Find-the-median-26"><span class="toc-item-num">26&nbsp;&nbsp;</span>Find the median</a></span></li><li><span><a href="#Check-equal" data-toc-modified-id="Check-equal-27"><span class="toc-item-num">27&nbsp;&nbsp;</span>Check equal</a></span></li><li><span><a href="#Specift-the-indice-you-need-to-add" data-toc-modified-id="Specift-the-indice-you-need-to-add-28"><span class="toc-item-num">28&nbsp;&nbsp;</span>Specift the indice you need to add</a></span></li><li><span><a href="#Find-indices-where-elements-should-be-inserted-to-maintain-order." data-toc-modified-id="Find-indices-where-elements-should-be-inserted-to-maintain-order.-29"><span class="toc-item-num">29&nbsp;&nbsp;</span>Find indices where elements should be inserted to maintain order.</a></span></li><li><span><a href="#Returns-the-indices-that-would-sort-an-array" data-toc-modified-id="Returns-the-indices-that-would-sort-an-array-30"><span class="toc-item-num">30&nbsp;&nbsp;</span>Returns the indices that would sort an array</a></span></li><li><span><a href="#Return-element-index-to-partition-by-and-other-index." data-toc-modified-id="Return-element-index-to-partition-by-and-other-index.-31"><span class="toc-item-num">31&nbsp;&nbsp;</span>Return element index to partition by and other index.</a></span></li><li><span><a href="#Calculate-the-n-th-discrete-difference-along-the-given-axis." data-toc-modified-id="Calculate-the-n-th-discrete-difference-along-the-given-axis.-32"><span class="toc-item-num">32&nbsp;&nbsp;</span>Calculate the n-th discrete difference along the given axis.</a></span></li><li><span><a href="#Permutation" data-toc-modified-id="Permutation-33"><span class="toc-item-num">33&nbsp;&nbsp;</span>Permutation</a></span></li></ul></div>

## Import numpy

In [1]:
import numpy

## Build a numpy array 

In [6]:
np.array([1,2,4,7,10])

array([ 1,  2,  4,  7, 10])

In [5]:
np.array([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

## Build a zero array

In [7]:
np.zeros((3,6),dtype=np.float32) #(3,6) is shape

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

## Build a one array 

In [8]:
np.ones(5,dtype=np.float32)

array([1., 1., 1., 1., 1.], dtype=float32)

##  A full array
You can determine content in the array

In [11]:
np.full((3),"Hello")

array(['Hello', 'Hello', 'Hello'], dtype='<U5')

## range (like range) 

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##  Find the values in the range

In [16]:
np.linspace(10,100,10)  #(start,end,number)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Generate value randomly from 0~1 

In [18]:
np.random.random((3,3)) #(3,3) is shape

array([[0.77636863, 0.55790351, 0.44640143],
       [0.08638662, 0.16573702, 0.58866942],
       [0.98442584, 0.99094086, 0.55868026]])

## Generate value randomly from normal distribution 

In [19]:
np.random.normal(0,10,(3,3)) #0 is mean  10 is standard deviation

array([[10.61523894,  9.18325346, -3.71899322],
       [ 6.92840905,  6.15057357,  6.1326105 ],
       [10.2438738 , -0.84750981, -1.93839968]])

## Generate values random in integars

In [20]:
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [0, 4, 4],
       [6, 2, 4]])

## Generate values in diagram

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## zero value 

In [23]:
np.empty((3,3,2)) #(dimension,row,col)

array([[[ 0.55555556,  1.11111111],
        [ 1.66666667,  2.22222222],
        [ 2.77777778,  3.33333333]],

       [[ 3.88888889,  4.44444444],
        [ 5.        ,  5.55555556],
        [ 6.11111111,  6.66666667]],

       [[ 7.22222222,  7.77777778],
        [ 8.33333333,  8.88888889],
        [ 9.44444444, 10.        ]]])

## Index, Slice 

In [26]:
x=np.random.randint(10,size=(3,4,5))
x

array([[[7, 6, 9, 1, 0],
        [1, 6, 8, 1, 7],
        [4, 5, 5, 8, 0],
        [2, 3, 1, 2, 6]],

       [[3, 4, 7, 8, 9],
        [0, 8, 1, 3, 6],
        [5, 2, 6, 8, 8],
        [7, 4, 3, 7, 5]],

       [[5, 3, 6, 9, 2],
        [6, 7, 0, 8, 0],
        [1, 6, 3, 2, 7],
        [1, 6, 6, 8, 4]]])

In [27]:
x[0]

array([[7, 6, 9, 1, 0],
       [1, 6, 8, 1, 7],
       [4, 5, 5, 8, 0],
       [2, 3, 1, 2, 6]])

In [29]:
x[0][0]

array([7, 6, 9, 1, 0])

In [30]:
x[0][0][0]

7

In [31]:
x[0,0,1]

6

In [32]:
x[0,0,:]

array([7, 6, 9, 1, 0])

## Reshape the array 

In [33]:
print(np.arange(10))
print(np.arange(10).reshape(5,2))

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [35]:
x=np.arange(10)
print(x.shape)
print(x[np.newaxis,:].shape) #GIve array extra axis

(10,)
(1, 10)


## Concatenate the array 

In [39]:
x1=np.array([1,2])
x2=np.array([3,4])
np.concatenate([x1,x2])

array([1, 2, 3, 4])

In [43]:
np.vstack((x1,x2))

array([[1, 2],
       [3, 4]])

In [44]:
np.hstack((x1,x2))

array([1, 2, 3, 4])

In [50]:
np.c_[x1,x2] #x1 two row x2 two row : reshape (2,2)

array([[1, 3],
       [2, 4]])

In [51]:
np.r_[x1,x2] #two row x1 two row x2 : reshape (0,4)

array([1, 2, 3, 4])

In [48]:
x1[np.newaxis,:]

array([[1, 2]])

## Split the array 

In [52]:
grid=np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
print(*np.vsplit(grid,[2]),sep='\n')

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [62]:
print(*np.hsplit(grid,[2]),sep='\n')

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## absolute 

In [64]:
x=np.arange(-2,3)
print(x)
print(np.absolute(x)) #as sames as np.abs()
print(np.abs(x))

[-2 -1  0  1  2]
[2 1 0 1 2]
[2 1 0 1 2]


## Exponential 

In [66]:
x=np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


## Power the array

In [68]:
x=np.array([1,2,3])
print(np.power(x,2))
print(np.power(x,3))

[1 4 9]
[ 1  8 27]


## Log 

In [125]:
x=np.array([1,10,100])
print(x)
print(np.log(x))    #nature log log(exp(x)) = x`

[  1  10 100]
[0.         2.30258509 4.60517019]


In [126]:
print(np.log10(x))

[0. 1. 2.]


In [127]:
print(np.log2(x))

[0.         3.32192809 6.64385619]


In [128]:
print(np.log1p(x))

[0.69314718 2.39789527 4.61512052]


In [130]:
print(np.logaddexp(x,x)) #Logarithm of the sum of exponentiations of the inputs.

[  1.69314718  10.69314718 100.69314718]


## Multipliy

In [78]:
x=np.arange(1,6)
y=np.arange(1,6)
print(np.multiply(x,y)) #return x*y
print(np.multiply(x,10,out=y)) #Change y to the result of x*10
print(y)

[ 1  4  9 16 25]
[10 20 30 40 50]
[10 20 30 40 50]


In [79]:
np.multiply.reduce(x)  #5*4*3*2*1

120

In [90]:
np.multiply.reduceat(x,[0,2,4]) #Base on [0,2,4] to split the data 
#[1,2,3,4,5] => [1,2], [3,4],[5] reduce separately

array([ 2, 12,  5])

In [92]:
np.multiply.outer(x,x) #change shape (5,5) x*x like 99 multiplication table

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

## Sum 

In [98]:
x=np.arange(10).reshape(2,5)
print(x)
print(x.sum())

[[0 1 2 3 4]
 [5 6 7 8 9]]
45


In [100]:
np.sum(x,axis=0)

array([ 5,  7,  9, 11, 13])

In [101]:
np.sum(x,axis=1)

array([10, 35])

## Max Min 

In [104]:
x=np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [105]:
np.max(x,axis=0)

array([5, 6, 7, 8, 9])

In [106]:
np.min(x,axis=1)

array([0, 5])

## argmax argmin

In [122]:
x=np.array([1,4,3,5,2,7,3])
print(np.argmax(x))  #Returns the indices of the maximum values along an axis.
print(x[5])

5
7


In [112]:
print(np.argmin(x))
print(x[0])

0
1


## Extract the percent value from the array

In [123]:
x=np.arange(10)
print(x)
print(np.percentile(x,[25,50,75]))

[0 1 2 3 4 5 6 7 8 9]
[2.25 4.5  6.75]


## Find the median 

In [124]:
x=np.arange(10)
print(np.median(x))

4.5


## Check equal

In [131]:
x=np.arange(5)
print(x)
print(np.equal(x,3))

[0 1 2 3 4]
[False False False  True False]


## Specift the indice you need to add

In [137]:
x=np.zeros(10)
np.add.at(x,[2,3],[5,6])
print(x)

[0. 0. 5. 6. 0. 0. 0. 0. 0. 0.]


## Find indices where elements should be inserted to maintain order. 

In [139]:
x=np.arange(10)
print(x)
print(np.searchsorted(x,2.5))

[0 1 2 3 4 5 6 7 8 9]
3


## Returns the indices that would sort an array

In [142]:
x=np.random.randint(0,10,5)
print(x)
print(np.argsort(x))
print(x[np.argsort(x)])

[2 5 3 4 6]
[0 2 3 1 4]
[2 3 4 5 6]


## Return element index to partition by and other index.

In [151]:
x=np.random.randint(0,10,5)
print(x)
print(np.argpartition(x,0))
print(np.argpartition(x,1))
print(np.argpartition(x,2))
print(np.argpartition(x,3))
print(np.argpartition(x,4))

[4 9 4 5 2]
[4 1 2 3 0]
[4 2 1 3 0]
[4 2 0 3 1]
[4 0 2 3 1]
[4 0 2 3 1]


##  Calculate the n-th discrete difference along the given axis.

In [155]:
x=np.array([1,2,4,7,-10])
print(x)   
print(np.diff(x))
print(np.diff(x,2))   #n represents that do n-th (n times) difference
print(np.diff(x,3))   #n代表做幾次的差值

[  1   2   4   7 -10]
[  1   2   3 -17]
[  1   1 -20]
[  0 -21]


## Permutation

重新排列組合，或者根據數字0,n-1隨機排列

In [2]:
#0~n-1 隨機排列
np.random.permutation(10)

array([2, 6, 9, 0, 4, 8, 5, 7, 1, 3])

In [3]:
#array內隨機排列
np.random.permutation([0,1,2])

array([0, 1, 2])